### ISSUE TITLE
Contenu étiquette "vous êtes" : Opérateurs de covoiturage

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage-vitrine#10]
Dans l'étiquette "Opérateur de covoiturage courte distance" présente sur toutes les pages, il manque le texte en dessous qui est : “Je veux être référencé dans le Registre afin d’être visible auprès des AOM”

**Comment by margot-sanchez** [comment]
Testé le 20 avril 2021 👍
