### ISSUE TITLE
🚥 Design / Navigation

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage-vitrine#11]
Coucou, 

Voici mes retours sur le design : 

**- Navigation - "_fil d'ariane_" lien actif :** 
Quand tu es sur une page, le texte du menu doit passer en en bleu france + un trait (voir exemple ci-dessous)

<img width="539" alt="Capture d’écran 2021-04-16 à 16 56 03" src="https://user-images.githubusercontent.com/76481140/115043330-b319cd00-9ed4-11eb-9d45-398016a47743.png">

**- Lien externe vers une page extérieure** 
Mettre une icône "flèche" quand on renvoi sur une page externe (cf le site https://design.incubateur.net/stats pour exemple) 
<img width="216" alt="Capture d’écran 2021-04-16 à 16 54 52" src="https://user-images.githubusercontent.com/76481140/115043160-7b128a00-9ed4-11eb-8574-64a89b4f5f77.png">
Il faudrait donc mettre ce picto sur les CTA suivants : 
- [x] Statistiques dans le menu navigation
- [x] sur la page d'accueil : Voir toutes les données * Voir la documentation * Voir toutes les statistiques  * En savoir plus (observatoire national du covoiturage) * Générer mon attestation * Signer la charte
- [x] Sur la page territoire : Guide territoires
- [x] Sur la page opérateurs : Guide opérateurs

**- Page d'accueil :** : changer l'alternance des bannière grises pour le bloc "nos autres outils en faveur du covoiturage au quotidien" => On aurait le bandeau gris sur Observatoire national du covoiturage et charte d'engagement

**- Page Opérateurs :** 

- [x] Classement par ordre alpha

**- Page "Qui sommes nous"** : mettre le même espacement entre tous les blocs

**Comment by jonathanfallon** [comment]
- [ ] Navigation : voir en fn des mises à jour du design system *
- [ ] Liens externes : voir en fn des mises à jour du design system *
- [x] Accueil : inverser l'alternance blanc/gris sur les outils
- [x] Opérateurs : classer par ordre alpha
- [x] Qui-sommes nous  

* La v1.0 du Design System vient de sortir, je vais faire la mise à jour et coller au design des éléments proposés. Ça facilite les mises à jour suivantes et assure la cohérence entre les différents sites utilisant le DSFR.

**Comment by margot-sanchez** [comment]
Action : par défaut les enlever + cibler uniquement les boutons (pas les liens dans le texte).

**Comment by margot-sanchez** [comment]
Testé le 27/05/2021

- [ ] navigation 
- [ ] Liens externes 

![image](https://user-images.githubusercontent.com/15428433/119859631-d8f3b200-bf15-11eb-8936-ba8434aa79db.png)
