### ISSUE TITLE
Contenu page Qui sommes-nous ? 

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage-vitrine#12]
- [x] Mettre les mêmes espacement entre chaque paragraphe et section

- [x] Supprimer les 3 chiffres clés de 2e ligne : 154 territoires sensibilisés, CO2 et classes de preuve

- [x] ajouter la précision suivante + lien : "à travers une certification des trajets, à l'aide de [classes de preuve de covoiturage](https://doc.covoiturage.beta.gouv.fr/territoires-beneficier-du-registre-de-preuve-de-covoiturage/classes-de-preuve-de-covoiturage)

**Comment by margot-sanchez** [comment]
Testé le 20 avril 2021 👍
