### ISSUE TITLE
Matomo

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage-vitrine#13]
- Aucune donnée encore remontée 🤨
- On apparait pas dans les sites référencés 🧐: 
[Capture d’écran 2021-04-16 à 14 57 37](https://user-images.githubusercontent.com/76481140/115050467-15c29700-9edc-11eb-8531-c98e1d83e96b.png)

**Comment by jonathanfallon** [comment]
Les données de vendredi sont affichées donc je suppose qu'il faut un peu de temps pour que ça arrive.
J'ai fait la demande pour l'affichage public des stats car je n'ai pas la main dessus.
https://startups-detat.slack.com/archives/C0KH4EBP0/p1618813343175800

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/115422987-b5926480-a1fd-11eb-8743-78524e023ea0.png)
Tada :)
