### ISSUE TITLE
Carte https://covoiturage.beta.gouv.fr/territoires/

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage-vitrine#19]
Bravo pour la carte 🤩👍 

Voici mes retours / suggestions : 
- Problème d'affichage sur Google Chrome (= je ne vois rien). En revanche, RAS sur Safari
- Ajouter un titre : **Découvrir les 65 territoires partenaires**
- Proposition d'ajouter un CTA en dessous de la carte : Rejoindre le Registre de preuve de covoiturage (=> lien formulaire de contact)
- Légende carte :  on a deux nuances de vert sur la carte. Il faudrait du coup légender le vert clair sur la carte. Si j'ai bien compris le vert clair = Région
- Ajouter la majuscule à Registre (légende)

**Comment by Datayama38** [comment]
Pour la légende, c'est le même vert. C'est simplement la transparence qui fait la différence à cause de la superposition des géométries

**Comment by jonathanfallon** [comment]
- [x] Ajouter un titre
- [x] Ajouter un CTA
- [x] Ajouter la majuscule
- [ ] Tests Chrome : en cours
- [ ] Couleurs différentes entre Régions et EPCI : pas de différence dans les données pour le moment.

**Comment by jonathanfallon** [comment]
Sorry, fermé automatiquement par la PR
