### ISSUE TITLE
Infolettre - modèle

### ISSUE THREAD

**Issue by lauriebequet** [betagouv/preuve-covoiturage-vitrine#24]
Jon 👋

Comme vu ensemble, tu trouveras sur Figma une proposition de mise en forme du formulaire d'inscription à la newsletter pour qu'on puisse le communiquer en externe.

Aujourd'hui, quand on communique à nos contacts le lien d'inscription, on a [cette présentation](https://b8e140eb.sibforms.com/serve/MUIEAHgW2vuF0uLwYJttS8mXF2H4Qx0vnPFnRKlWrw69lfrkQqrv3KLlZJiJ1mD2td4fznXJVLeF0t1Rj_1mSrSMvZoA64aaJ8RHG-rS_uhwLxQwlpceRWJEzCkpGXj_YZLLO9_Qusm8zAVdu_jh4YqMPj1jeVFNYczhuW1L5kF8aA081AE8RoT7WZoxK6xum2hgIQd00oh9hpUe) : 
![Capture d’écran 2021-04-28 à 18 53 41](https://user-images.githubusercontent.com/76481140/116442671-126fc980-a853-11eb-9b15-b796b79748e6.png)

=> Pas terrible car aucun texte etc.

A+

**Comment by margot-sanchez** [comment]
Le lien vers Figma : https://www.figma.com/file/xZAEUDJdpcUnmObJBLNDfd/Site-vitrine-RPC

**Comment by margot-sanchez** [comment]
Faire uniquement un gros bouton dans le footer qui amène sur une nouvelle page.

**Comment by jonathanfallon** [comment]
PR #29

**Comment by margot-sanchez** [comment]
Testé le 01/06/2021 👍

**Comment by margot-sanchez** [comment]
![image](https://user-images.githubusercontent.com/15428433/120286051-28dbcb80-c2be-11eb-8be0-163b8f000301.png)
