### ISSUE TITLE
Retours site vitrine - liens dysfonctionnels 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage-vitrine#5]
#### Notre autre outils

- [x] Liens observatoire -->

- [x] Liens signer la charte  --> 
#### Vous êtes
- [x] Lien devenir partenaire opérateur --> 
#### Footer
- [x] Lien twitter de betagouv et pas du RPC --> 
- [x] Lien youtube manquant --> 
- [x] Lien linkedin faux --> https://www.linkedin.com/company/registre-de-preuve-de-covoiturage
- [x] Lien RSS faux --> 

### Territoires
- [x] Lien guide territoire faux --> 

### Opérateurs 
- [x] Lien guide opérateur faux --> 

### Quisommes-nous ? 
- [x] "voir les autres outils" --> (mettre une balise sur la page d'accueil)

**Comment by jonathanfallon** [comment]
@margot-sanchez c'est OK. Tu peux tester sur https://covoiturage.beta.gouv.fr/

**Comment by margot-sanchez** [comment]
Testé le 20 avril 2021 👍
