### ISSUE TITLE
ERROR: Couldn't find env file

### ISSUE THREAD

**Issue by Datayama38** [betagouv/preuve-covoiturage-vitrine#9]
Il a l'air de manquer un fichier .env.example pour savoir quoi configurer après avoir cloner le repo.
J'obtiens cette erreur lorsque je lance la commande docker-compose up server
ERROR: Couldn't find env file

**Comment by jonathanfallon** [comment]
Sorry... c'est fait.
L'explication est dans le fichier directement.

https://github.com/betagouv/preuve-covoiturage-vitrine/commit/d7ad97583bc222fbf9c99979c04cb2b04a9cec62
